#include <stdio.h>
#include "hocdec.h"
#define IMPORT extern __declspec(dllimport)
IMPORT int nrnmpi_myid, nrn_nobanner_;

extern void _Im_ms_reg();
extern void _NO_reg();
extern void _bk_ch_reg();
extern void _bk_fs_reg();
extern void _bk_ms_reg();
extern void _ca_ch_reg();
extern void _cadyn_fs_reg();
extern void _cadyn_ms_reg();
extern void _cal12_ms_reg();
extern void _cal13_ms_reg();
extern void _cal_ch_reg();
extern void _caldyn_ms_reg();
extern void _can_fs_reg();
extern void _can_ms_reg();
extern void _cap_ch_reg();
extern void _caq_fs_reg();
extern void _caq_ms_reg();
extern void _car_fs_reg();
extern void _car_ms_reg();
extern void _cat32_ms_reg();
extern void _cat33_ms_reg();
extern void _concACh_reg();
extern void _concDA_reg();
extern void _hcn12_ch_reg();
extern void _hd_lts_reg();
extern void _im_lts_reg();
extern void _it_lts_reg();
extern void _kaf_fs_reg();
extern void _kaf_lts_reg();
extern void _kaf_ms_reg();
extern void _kas_fs_reg();
extern void _kas_ms_reg();
extern void _kcnq_ch_reg();
extern void _kdb_lts_reg();
extern void _kdr_fs_reg();
extern void _kdr_lts_reg();
extern void _kdr_ms_reg();
extern void _kdrb_lts_reg();
extern void _kir23_ch_reg();
extern void _kir23_lts_reg();
extern void _kir2_ch_reg();
extern void _kir_fs_reg();
extern void _kir_ms_reg();
extern void _kv2_ch_reg();
extern void _kv4_ch_reg();
extern void _na2_ch_reg();
extern void _na3_lts_reg();
extern void _na_ch_reg();
extern void _naf_fs_reg();
extern void _naf_lts_reg();
extern void _naf_ms_reg();
extern void _par_ggap_reg();
extern void _sk_ch_reg();
extern void _sk_fs_reg();
extern void _sk_ms_reg();
extern void _tmgabaa_reg();
extern void _tmglut_reg();
extern void _tmglut_M1RH_D1_reg();
extern void _tmglut_double_reg();
extern void _vecevent_reg();

void modl_reg(){
	//nrn_mswindll_stdio(stdin, stdout, stderr);
    if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
	fprintf(stderr, "Additional mechanisms from files\n");

fprintf(stderr," Im_ms.mod");
fprintf(stderr," NO.mod");
fprintf(stderr," bk_ch.mod");
fprintf(stderr," bk_fs.mod");
fprintf(stderr," bk_ms.mod");
fprintf(stderr," ca_ch.mod");
fprintf(stderr," cadyn_fs.mod");
fprintf(stderr," cadyn_ms.mod");
fprintf(stderr," cal12_ms.mod");
fprintf(stderr," cal13_ms.mod");
fprintf(stderr," cal_ch.mod");
fprintf(stderr," caldyn_ms.mod");
fprintf(stderr," can_fs.mod");
fprintf(stderr," can_ms.mod");
fprintf(stderr," cap_ch.mod");
fprintf(stderr," caq_fs.mod");
fprintf(stderr," caq_ms.mod");
fprintf(stderr," car_fs.mod");
fprintf(stderr," car_ms.mod");
fprintf(stderr," cat32_ms.mod");
fprintf(stderr," cat33_ms.mod");
fprintf(stderr," concACh.mod");
fprintf(stderr," concDA.mod");
fprintf(stderr," hcn12_ch.mod");
fprintf(stderr," hd_lts.mod");
fprintf(stderr," im_lts.mod");
fprintf(stderr," it_lts.mod");
fprintf(stderr," kaf_fs.mod");
fprintf(stderr," kaf_lts.mod");
fprintf(stderr," kaf_ms.mod");
fprintf(stderr," kas_fs.mod");
fprintf(stderr," kas_ms.mod");
fprintf(stderr," kcnq_ch.mod");
fprintf(stderr," kdb_lts.mod");
fprintf(stderr," kdr_fs.mod");
fprintf(stderr," kdr_lts.mod");
fprintf(stderr," kdr_ms.mod");
fprintf(stderr," kdrb_lts.mod");
fprintf(stderr," kir23_ch.mod");
fprintf(stderr," kir23_lts.mod");
fprintf(stderr," kir2_ch.mod");
fprintf(stderr," kir_fs.mod");
fprintf(stderr," kir_ms.mod");
fprintf(stderr," kv2_ch.mod");
fprintf(stderr," kv4_ch.mod");
fprintf(stderr," na2_ch.mod");
fprintf(stderr," na3_lts.mod");
fprintf(stderr," na_ch.mod");
fprintf(stderr," naf_fs.mod");
fprintf(stderr," naf_lts.mod");
fprintf(stderr," naf_ms.mod");
fprintf(stderr," par_ggap.mod");
fprintf(stderr," sk_ch.mod");
fprintf(stderr," sk_fs.mod");
fprintf(stderr," sk_ms.mod");
fprintf(stderr," tmgabaa.mod");
fprintf(stderr," tmglut.mod");
fprintf(stderr," tmglut_M1RH_D1.mod");
fprintf(stderr," tmglut_double.mod");
fprintf(stderr," vecevent.mod");
fprintf(stderr, "\n");
    }
_Im_ms_reg();
_NO_reg();
_bk_ch_reg();
_bk_fs_reg();
_bk_ms_reg();
_ca_ch_reg();
_cadyn_fs_reg();
_cadyn_ms_reg();
_cal12_ms_reg();
_cal13_ms_reg();
_cal_ch_reg();
_caldyn_ms_reg();
_can_fs_reg();
_can_ms_reg();
_cap_ch_reg();
_caq_fs_reg();
_caq_ms_reg();
_car_fs_reg();
_car_ms_reg();
_cat32_ms_reg();
_cat33_ms_reg();
_concACh_reg();
_concDA_reg();
_hcn12_ch_reg();
_hd_lts_reg();
_im_lts_reg();
_it_lts_reg();
_kaf_fs_reg();
_kaf_lts_reg();
_kaf_ms_reg();
_kas_fs_reg();
_kas_ms_reg();
_kcnq_ch_reg();
_kdb_lts_reg();
_kdr_fs_reg();
_kdr_lts_reg();
_kdr_ms_reg();
_kdrb_lts_reg();
_kir23_ch_reg();
_kir23_lts_reg();
_kir2_ch_reg();
_kir_fs_reg();
_kir_ms_reg();
_kv2_ch_reg();
_kv4_ch_reg();
_na2_ch_reg();
_na3_lts_reg();
_na_ch_reg();
_naf_fs_reg();
_naf_lts_reg();
_naf_ms_reg();
_par_ggap_reg();
_sk_ch_reg();
_sk_fs_reg();
_sk_ms_reg();
_tmgabaa_reg();
_tmglut_reg();
_tmglut_M1RH_D1_reg();
_tmglut_double_reg();
_vecevent_reg();
}
