import numpy as np


def CreateCubeMesh(fileName,centrePoint,sideLen, description=None):

  if(type(centrePoint) is not np.ndarray):
    centrePoint = np.array(centrePoint)
    
  print("Creating cube mesh")
  print("File: " + str(fileName))
  print("Centre: " + str(centrePoint))
  print("Side: " + str(sideLen))
  print("Description: " + str(description))
    
  vertex = np.array([[0.0,  0.0,  0.0],
                     [0.0,  0.0,  1.0],
                     [0.0,  1.0,  0.0],
                     [0.0,  1.0,  1.0],
                     [1.0,  0.0,  0.0],
                     [1.0,  0.0,  1.0],
                     [1.0,  1.0,  0.0],
                     [1.0,  1.0,  1.0]])

  # Centre cube
  vertex -= np.array([0.5,0.5,0.5])

  # Scale the cube to right size
  vertex *= sideLen 

  # Position cube

  vertex += centrePoint

  vertex *= 1e6 # The other obj files are in micrometers, so convert :(
  
  normalStr = "vn  0.0  0.0  1.0\n" \
            + "vn  0.0  0.0 -1.0\n" \
            + "vn  0.0  1.0  0.0\n" \
            + "vn  0.0 -1.0  0.0\n" \
            + "vn  1.0  0.0  0.0\n" \
            + "vn -1.0  0.0  0.0\n"

  faceStr = "f  1//2  7//2  5//2\n" \
          + "f  1//2  3//2  7//2\n" \
          + "f  1//6  4//6  3//6\n" \
          + "f  1//6  2//6  4//6\n" \
          + "f  3//3  8//3  7//3\n" \
          + "f  3//3  4//3  8//3\n" \
          + "f  5//5  7//5  8//5\n" \
          + "f  5//5  8//5  6//5\n" \
          + "f  1//4  5//4  6//4\n" \
          + "f  1//4  6//4  2//4\n" \
          + "f  2//1  6//1  8//1\n" \
          + "f  2//1  8//1  4//1\n"

  with open(fileName,'wt') as f:
    f.write("# Generated by CreateCubeMesh.py\n")
    f.write("# " + str(description) + "\n\n")

    f.write("g cube\n\n")

    for row in vertex:
      f.write("v %f %f %f\n" % tuple(row))

    f.write("\n" + normalStr)

    f.write("\n" + faceStr)

    
if __name__ == "__main__":
  
  CreateCubeMesh(fileName="test-cube.obj",
                 centrePoint=[1,2,3],
                 sideLen=2,
                 description="This is a test cube")
