#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _Kv3_ch_reg(void);
extern void _bk_ch_reg(void);
extern void _bk_fs_reg(void);
extern void _bk_ms_reg(void);
extern void _ca_ch_reg(void);
extern void _cadyn_fs_reg(void);
extern void _cadyn_ms_reg(void);
extern void _cal12_ms_reg(void);
extern void _cal13_ms_reg(void);
extern void _cal_ch_reg(void);
extern void _caldyn_ms_reg(void);
extern void _can_fs_reg(void);
extern void _can_ms_reg(void);
extern void _cap_ch_reg(void);
extern void _caq_fs_reg(void);
extern void _caq_ms_reg(void);
extern void _car_fs_reg(void);
extern void _car_ms_reg(void);
extern void _cat32_ms_reg(void);
extern void _cat33_ms_reg(void);
extern void _h_lts_reg(void);
extern void _hcn12_ch_reg(void);
extern void _im_lts_reg(void);
extern void _it_lts_reg(void);
extern void _kaf_fs_reg(void);
extern void _kaf_ms_reg(void);
extern void _kas_fs_reg(void);
extern void _kas_ms_reg(void);
extern void _kcnq_ch_reg(void);
extern void _kdr_fs_reg(void);
extern void _kdr_ms_reg(void);
extern void _kdrbca1_lts_reg(void);
extern void _kir2_ch_reg(void);
extern void _kir_fs_reg(void);
extern void _kir_ms_reg(void);
extern void _kv2_ch_reg(void);
extern void _kv4_ch_reg(void);
extern void _na2_ch_reg(void);
extern void _na3n_lts_reg(void);
extern void _na_ch_reg(void);
extern void _naf_fs_reg(void);
extern void _naf_ms_reg(void);
extern void _par_ggap_reg(void);
extern void _sk_ch_reg(void);
extern void _sk_fs_reg(void);
extern void _sk_ms_reg(void);
extern void _tmampa_reg(void);
extern void _tmgabaa_reg(void);
extern void _tmglut_reg(void);
extern void _tmnmda_reg(void);
extern void _vecevent_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," snudda/data/cellspecs/mechanisms/Kv3_ch.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/bk_ch.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/bk_fs.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/bk_ms.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/ca_ch.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/cadyn_fs.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/cadyn_ms.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/cal12_ms.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/cal13_ms.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/cal_ch.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/caldyn_ms.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/can_fs.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/can_ms.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/cap_ch.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/caq_fs.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/caq_ms.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/car_fs.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/car_ms.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/cat32_ms.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/cat33_ms.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/h_lts.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/hcn12_ch.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/im_lts.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/it_lts.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/kaf_fs.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/kaf_ms.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/kas_fs.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/kas_ms.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/kcnq_ch.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/kdr_fs.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/kdr_ms.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/kdrbca1_lts.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/kir2_ch.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/kir_fs.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/kir_ms.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/kv2_ch.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/kv4_ch.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/na2_ch.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/na3n_lts.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/na_ch.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/naf_fs.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/naf_ms.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/par_ggap.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/sk_ch.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/sk_fs.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/sk_ms.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/tmampa.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/tmgabaa.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/tmglut.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/tmnmda.mod");
    fprintf(stderr," snudda/data/cellspecs/mechanisms/vecevent.mod");
    fprintf(stderr, "\n");
  }
  _Kv3_ch_reg();
  _bk_ch_reg();
  _bk_fs_reg();
  _bk_ms_reg();
  _ca_ch_reg();
  _cadyn_fs_reg();
  _cadyn_ms_reg();
  _cal12_ms_reg();
  _cal13_ms_reg();
  _cal_ch_reg();
  _caldyn_ms_reg();
  _can_fs_reg();
  _can_ms_reg();
  _cap_ch_reg();
  _caq_fs_reg();
  _caq_ms_reg();
  _car_fs_reg();
  _car_ms_reg();
  _cat32_ms_reg();
  _cat33_ms_reg();
  _h_lts_reg();
  _hcn12_ch_reg();
  _im_lts_reg();
  _it_lts_reg();
  _kaf_fs_reg();
  _kaf_ms_reg();
  _kas_fs_reg();
  _kas_ms_reg();
  _kcnq_ch_reg();
  _kdr_fs_reg();
  _kdr_ms_reg();
  _kdrbca1_lts_reg();
  _kir2_ch_reg();
  _kir_fs_reg();
  _kir_ms_reg();
  _kv2_ch_reg();
  _kv4_ch_reg();
  _na2_ch_reg();
  _na3n_lts_reg();
  _na_ch_reg();
  _naf_fs_reg();
  _naf_ms_reg();
  _par_ggap_reg();
  _sk_ch_reg();
  _sk_fs_reg();
  _sk_ms_reg();
  _tmampa_reg();
  _tmgabaa_reg();
  _tmglut_reg();
  _tmnmda_reg();
  _vecevent_reg();
}
