#!/bin/bash -l
#SBATCH --partition=main
#SBATCH -o log/create-network-cur-inj-%j-output.txt
#SBATCH -e log/create-network-cur-inj-%j-error.txt
#SBATCH -t 0:19:00
#SBATCH -J Snudda
#SBATCH -A snic2021-5-492
#SBATCH --nodes=1
#SBATCH --tasks-per-node=64

module load snic-env

export IPYTHONDIR="/cfs/klemming/scratch/${USER:0:1}/$USER/.ipython"
rm -r $IPYTHONDIR
export IPYTHON_PROFILE=default
source $HOME/Snudda/snudda_env/bin/activate

srun ./Dardel_create_FS_network-cur-inj.sh
