#!/bin/bash -l
#SBATCH --partition=main
#SBATCH -o log/runSnudda-%j-output.txt
#SBATCH -e log/runSnudda-%j-error.txt
#SBATCH -t 01:00:00
#SBATCH -J Snudda_PD
#SBATCH -A snic2022-5-245
#SBATCH --nodes=1
#SBATCH --tasks-per-node=128
#SBATCH --mail-type=ALL

module load snic-env

export IPYTHONDIR="/cfs/klemming/scratch/${USER:0:1}/$USER/.ipython"
rm -r $IPYTHONDIR
export IPYTHON_PROFILE=default
source $HOME/Snudda/snudda_env/bin/activate

srun ./Dardel_PD0_PD2_networks.sh
