#!/bin/bash -l
#SBATCH --partition=main
#SBATCH -o log/Input-%j-output.txt
#SBATCH -e log/Input-%j-error.txt
#SBATCH -t 0:30:00
#SBATCH -J SnuddaInput
#SBATCH -A snic2022-5-245
#SBATCH --nodes=1
#SBATCH --tasks-per-node=64

module load snic-env

export IPYTHONDIR="/cfs/klemming/scratch/${USER:0:1}/$USER/.ipython"
rm -r $IPYTHONDIR
export IPYTHON_PROFILE=default
source $HOME/Snudda/snudda_env/bin/activate

srun ./Dardel_setupInput.sh
