name: Unit networks

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: actions/cache@v1
      with :
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install MPI
      run: |
        sudo apt-get update
        sudo apt-get install openmpi-bin libopenmpi-dev
    - name: Install NEURON
      run: |
        wget https://neuron.yale.edu/ftp/neuron/versions/v7.7/7.7.2/nrn-7.7.2.x86_64-linux-py-37-36-35-27.deb
        sudo dpkg -i nrn-7.7.2.x86_64-linux-py-37-36-35-27.deb
        export PYTHONPATH=/usr/local/nrn/lib/python
        # python -c "help('modules')"
        # echo "PYTHONPATH=$PYTHONPATH"
        # echo "/usr/local/nrn contains:"
        # ls /usr/local/nrn
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
        pip install -e .  # Install snudda as package on the build system.
    - name: Run unittests and code coverage
      run: |
        coverage run -m unittest discover -v -s ./tests
        coverage xml
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
